version: '3'
services:
  client:
    build: ../dt-client-bytes
    depends_on:
      - mqtt-broker
      - twin
    environment:
      - RUST_LOG=info
      - MQTT_BROKER_ADDRESS=mqtt-broker
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_QOS=1
      - MQTT_CLIENT_BUFFER_BYTE_SIZE=8
      - MQTT_CLIENT_MESSAGES_TO_SEND=100
      - MQTT_CLIENT_MESSAGE_DELAY_MS=50
  twin:
    build: .
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-broker
      - MQTT_BROKER_PORT=1883
      - MQTT_INSTANCE_QOS=0
      - RUST_LOG=info
      - DB_ADDRESS=scylla-db:9042
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
    networks:
      - default
    restart: always
  twin-webserver:
    build: ../dt-instance-webserver/.
    image: "dt-instance-webserver"
    restart: always
    depends_on:
      - scylla-db
      - scylla-manager
    ports:
      - "8080:8080"
    environment: 
      - RUST_LOG=info
      - SERVER_ADDRESS=0.0.0.0:8081
      - DB_ADDRESS=scylla-db:9042
      - SECRET_KEY=Xqv8jTGLxT
      - TWIN_INSTANCE=38162cb0-e585-43d7-b55d-5c240b2bfb7c
    command: sh -c './wait-for scylla-db:9042 -- dt-instance'
  mqtt-broker:
    image: "opendigitaltwin/mosquitto:latest"
    container_name: mqtt-broker
    # expose: [1883]
    ports:
      - "1883:1883"
    networks:
      - default
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
    restart: always
  scylla-manager:
    image: scylladb/scylla-manager
    container_name: scylla-manager
    depends_on:
      - scylla-db
    networks:
      - default
    links:
      - "scylla-db:scylla-manager-db"
  scylla-db:
    image: scylladb/scylla
    container_name: scylla-db
    expose: [9042]
    networks:
      - default
    volumes:
      - ./shared/db:/db
      - ./shared/dbinit.sh:/dbinit.sh
networks:
  default:
