version: '3'
services:
  twin:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mqtt-broker
    volumes:
      - .:/code
    networks:
      - default
  twin-webserver:
    build: ../dt-instance-webserver/.
    image: "dt-instance-webserver"
    depends_on:
      - scylla-db
      - scylla-manager
    ports:
      - "8080:8080"
    environment: 
      - RUST_LOG=info
      - SERVER_ADDRESS=0.0.0.0:8080
      - DB_ADDRESS=scylla-db:9042
      - SECRET_KEY=Xqv8jTGLxT
      - TWIN_INSTANCE=1
  mqtt-broker:
    image: "eclipse-mosquitto:latest"
    ports:
      - "1883:1883"
    networks:
      - default
  scylla-manager:
    image: scylladb/scylla-manager
    container_name: scylla-manager
    depends_on:
      - scylla-db
    networks:
      - default
    links:
      - "scylla-db:scylla-manager-db"
  scylla-db:
    image: scylladb/scylla
    container_name: scylla-db
    expose: [9042]
    networks:
      - default
    volumes:
      - ./shared/db:/db
      - ./shared/dbinit.sh:/dbinit.sh
networks:
  default:
