version: '3'
services:
  dt-instance:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  mqtt-broker:
    image: "eclipse-mosquitto:latest"
    expose: [1883]
  db-cassandra:
    image: "cassandra"
    expose: [9042]

